// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5-kAeVn9_iH5qG7JyEaUs2itM4yNAWYc',
    appId: '1:14919150628:web:6f17edb9c35ada3c237cb1',
    messagingSenderId: '14919150628',
    projectId: 'skullking-e6a1f',
    authDomain: 'skullking-e6a1f.firebaseapp.com',
    databaseURL: 'https://skullking-e6a1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skullking-e6a1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS03hdL0tsoom0pmHjxmPd6mXqrYnRvGs',
    appId: '1:14919150628:android:ef4221b57fe56e5f237cb1',
    messagingSenderId: '14919150628',
    projectId: 'skullking-e6a1f',
    databaseURL: 'https://skullking-e6a1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skullking-e6a1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLP-3iqMaeNBLkMeIUAeaMnJ8jxHcZlVk',
    appId: '1:14919150628:ios:476fccc9863ccb79237cb1',
    messagingSenderId: '14919150628',
    projectId: 'skullking-e6a1f',
    databaseURL: 'https://skullking-e6a1f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'skullking-e6a1f.appspot.com',
    iosClientId: '14919150628-i31h2jor57e0gcfcau2mqo59ocqog4dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pirateApp',
  );
}
